/**
 * Defines all shared TypeScript interfaces and types for the application.
 * This ensures data consistency from generation to database storage.
 */

// Represents the structure of a quiz question generated by the AI.
export interface Question {
  question: string;
  options: { [key: string]: string; };
  answer: string;
  explanation: string;
  category: string;
  topic: string;
  question_type?: string; // 'multiple_choice' or 'true_false'
}


// Represents a node in the persona hierarchy.
interface PersonaNode {
  key: string;
  displayName: string;
  subCategories?: PersonaNode[];
}

// Defines the structure for the MasterPersonas object.
export interface PersonaConfig {
  [personaKey: string]: {
    displayName: string;
    subCategories: PersonaNode[];
  };
}

// Represents the structure of a job as stored in the quiz_jobs table.
export interface QuizJob {
  id: string;
  persona: string;
  category: string;
  topic: string;
  // Add these two optional properties
  category_display_name?: string;
  topic_display_name?: string;
  question_format: string;
  generation_date: string;
  status: string;
  step: number;
  data: any;
  error_message?: string;
  created_at: string;
  updated_at: string;
}



// Represents a successfully uploaded video record.
export interface UploadedVideo {
  id: string;
  job_id: string;
  youtube_video_id: string;
  title: string;
  description?: string;
  tags: string[];
  view_count: number;
  uploaded_at: Date;
}

// Represents the structure of a visual theme.
export interface Theme {
  name: string;
  fontFamily: string;
  page: {
    background: string;
  };
  text: {
    primary: string;    // For questions, main content
    secondary: string;  // For footers, muted text
    onAccent: string;   // For text on colored buttons/backgrounds
  };
  button: {
    background: string;
    text: string;
  };
  feedback: {
    correct: string;    // Background for correct answers
  };
}