/**
 * Defines all shared TypeScript interfaces and types for the application.
 * This ensures data consistency from generation to database storage.
 */

// Represents the structure of a quiz question generated by the AI.
export interface Question {
  question: string;
  options: { [key: string]: string; };
  answer: string;
  explanation: string;
  category: string;
  topic: string;
}


// Represents a node in the curriculum hierarchy.
interface CurriculumNode {
  key: string;
  displayName: string;
  subCategories?: CurriculumNode[];
}

// Defines the structure for the MasterCurriculum object.
export interface Curriculum {
  [personaKey: string]: {
    displayName:string;
    structure: CurriculumNode[];
  };
}

// Represents the structure of a job as stored in the quiz_jobs table.
export interface QuizJob {
  id: string;
  persona: string;
  category: string;
  topic: string;
  // Add these two optional properties
  category_display_name?: string;
  topic_display_name?: string;
  question_format: string;
  difficulty: string;
  generation_date: string;
  status: string;
  step: number;
  data: any;
  error_message?: string;
  created_at: string;
  updated_at: string;
}



// Represents a successfully uploaded video record.
export interface UploadedVideo {
  id: string;
  job_id: string;
  youtube_video_id: string;
  title: string;
  description?: string;
  tags: string[];
  view_count: number;
  uploaded_at: Date;
}

// Represents the structure of a visual theme.
export interface Theme {
  name: string;
  FONT_FAMILY: string;
  COLOR_BG_DARK: string;
  COLOR_BG_LIGHT: string;
  COLOR_TEXT_PRIMARY: string;
  COLOR_BUTTON_BG: string;
  COLOR_CORRECT_BG: string;
  COLOR_CORRECT_TEXT: string;
  MUTED_TEXT_COLOR: string;
}
