/**
 * Defines all shared TypeScript interfaces and types for the application.
 * This ensures data consistency from generation to database storage.
 */

// Represents the structure of a quiz question generated by the AI.
export interface Question {
  question: string;
  options: { [key: string]: string; };
  answer: string;
  explanation: string;
  category: string;
  topic: string;
}

// Represents a node in the curriculum hierarchy.
interface CurriculumNode {
  key: string;
  displayName: string;
  subCategories?: CurriculumNode[];
}

// Defines the structure for the MasterCurriculum object.
export interface Curriculum {
  [personaKey: string]: {
    displayName:string;
    structure: CurriculumNode[];
  };
}

// Represents the structure of a job as stored in the quiz_jobs table.
export interface QuizJob {
  id: string;
  persona: 'vocabulary' | 'current_affairs' | 'test_prep' | 'general_knowledge' | 'language_learning';
  category: string;
  question_format: string;
  difficulty: 'beginner' | 'easy' | 'medium' | 'hard' | 'expert';
  language: string;
  target_audience: string;
  status: string;
  step: number;
  tags: string[];
  data: {
    question: Question;
    frameUrls?: string[];
    videoUrl?: string;
    videoSize?: number; // 💡 FIX: Added videoSize property
    youtube_video_id?: string;
    topic_display_name?: string;
    category_display_name?: string;
    generation_date?: string;
  };
  error_message?: string;
  created_at: Date;
  updated_at: Date;
}

// Represents a successfully uploaded video record.
export interface UploadedVideo {
  id: string;
  job_id: string;
  youtube_video_id: string;
  title: string;
  description?: string;
  tags: string[];
  view_count: number;
  uploaded_at: Date;
}

// Represents the structure of a visual theme.
export interface Theme {
  name: string;
  FONT_FAMILY: string;
  COLOR_BG_DARK: string;
  COLOR_BG_LIGHT: string;
  COLOR_TEXT_PRIMARY: string;
  COLOR_BUTTON_BG: string;
  COLOR_CORRECT_BG: string;
  COLOR_CORRECT_TEXT: string;
  MUTED_TEXT_COLOR: string;
}
